name: CI Pipeline

on:
  push:
    branches: [main]
    pull_request:
      branches: [main]  

jobs:
matrix-pip:
name: Train and Save the model
runs-on: ubuntu-latest
Strategy:
  matrix:
    python-version: [3.11, 3.12]
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: upgrade pip
        run: python -a pip install --upgrade pip setuptools wheel


      - name: Train the model
        run: |
          python train.py
          ls -ls artifact@v4
        with:
          name: ml-artifacts-${{ matrix.python }}-${{ github.run_id }}
          path: artifacts
